name: my-job-portal-ui
on:
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    name: Build
    strategy:
      fail-fast: true
    runs-on: macos-latest

    steps:
      - name: Checkout repository
      - uses: actions/checkout@v3

      - name: Download binary
      - uses: actions/setup-node@v3
        with:
          node-version: '16.10.0'

      - name: Install dependencies
        run: npm ci

      - name: Static analysis
        run: |
          echo "Linting in progress..."
          npm run lint
          echo "Type checking in progress..."
          npm run check:typings

      - name: Create artifacts
        run: |
          echo "Running production build..."
          npm run build:prod

  test:
    name: Test
    needs: build
    runs-on: macos-latest

    steps:
      - name: Unit Test
        run: |
          echo "Unit Tests are running..."

  security:
    name: Security Scan
    needs: test
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run SAST scan
        uses: AppThreat/sast-scan-action@v1.0.0
        with:
          type: nodejs

      - name: Run SCA scan
        uses: snyk/actions/node@master
        continue-on-error: true
        with:
          languages: ${{ matrix.node-version }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


